page_list = [[
    # 'tsaiingwen',
    # 'ETtoday',
    # 'tiktoktaiwan',
    # 'TerryGou1018',
    # 'myudn',
    # '100044226139684',
    # 'DoctorKoWJ',
    # 'mohw.gov.tw',
    # '100044207960749',
    # '100044580272976',
    # 'twherohan',
    # 'namewee',
    # 'posenkid',
    # 'debatelo',
    # 'ETtodaySTAR',
    # 'NTDChinese',
    # 'CTimefans',
    # 'setnews',
    # 'noc.tpe',
    # 'thisgroupofpeople',
    # 'YESRANGER',
    # 'RayDuEnglish',
    # 'WithGaLoveTaiwan',
    # 'jay',
    # 'JoemanStation',
    # 'Muyao4',
    # 'etman0909',
    # 'amogood2.0',
    # 'ruruspiano',
    # 'HuangHuangBrother',
    # 'Chienseating',
    # 'fumeancats',
    # 'Wackyboys.Fans',
    # 'YahooTWNews',
    # 'appledaily.tw',
    # 'news.ebc',
    # 'ashin555',
    # '%E7%88%86%E6%96%99%E5%85%AC%E7%A4%BE-162608724089621',
    # 'duncanlindesign',
    # 'BuzzHandCom',
    # 'EBCbuzz',
    # 'tw.vonvon.me',
    # 'tos.zh',
    # '711open',
    # 'supertastesupertaste',
    # 'BeautiesOfLifeOfficial',
    # 'FanFan.official',
    # 'SoniaSuiOfficialFanPage',
    'nexttw',
    'starbuckstaiwan',
    'JJLin',
    'baxuan.mei',
    'ooppeennkkll9999',
    'MaYingjeou',
    'ETtodayBEAUTY',
    'ETtodayPETS',
    'bailingguonews',
    'ABAO825',
    'AlyssaClub',
    'ROYCHIU1014',
],[
    'atunemusichebe',
    's3beauty',
    'jackywuofficial',
    'Gina.Hello',
    'amber.fans',
    'Soon0930',
    'may8572fit',
    'icooktw',
    '0604rainie',
    'donghannah',
    'Mr.Player.tw',
    'FamilyMart',
    'sandymandy0731',
    'fanslingin',
    'BaiChiGongZhu',
    'dpptw',
    'TPPfanpage',
    'newpowerparty',
    'ironprofessorchan',
    'LawyerHandyChiu',
    'pcyeh.NTU',
    'froggychiu',
    'kylie.wang.16',
    'fanamericantime',
    'kcfor2016',
    'Statebuilding.tw',
    'leeyang0812',
    'ChiLin0118',
    'XiaoyuSung1122',
    'WenChiangLiao',
    'Weibird.official',
    'DavidTao.fans',
    'AiYiLiangEve',
    'mykmt',
    'crowndmei',
    'ZyNXyZ',
    'geevideo',
    'dream76843',
    'miaopoya.sdp',
    'WangWeiChen.0703',
    'eltasports',
    'VKstyle',
    'john.barthelette',
    'turtledrawturtle',
    'dayang2013',
    'chingte',
    'C.T.H39',
    'hsien24',
    'translatebyHANEKO',
    'limfreddy',
    'fluffytw',
    'brianstandup',
    'strnetworkasia',
    'lunglungtragiclife',
    'udnSTYLE',
    '100044175532205',
    'Howardinterprets',
    'FireEX',
    'muscleguyTW',
    'NasiLoveMusic',
],[
    'leehom',
    'KK486',
    'tsaigray2018',
    'ZhongMingXuan',
    'OTR.HC.Wang',
    'ABGKitchen',
    '%E8%80%81%E9%AB%98%E8%88%87%E5%B0%8F%E8%8C%89-Mr-Mrs-Gao-109557440516292',
    'wecook123',
    '100044363202846',
    '100044142473925',
    '100044464928251',
    'howfunofficial',
    'capoocat',
    'PKpotterking',
    'onionman4704',
    'rosalinakitchen',
    'lyla.0814',
    'banai.shunz',
    'liketaitai',
    '77%E8%80%81%E5%A4%A7-268981440270853',
    'anjoupikachu',
    'YummyDayTW',
    'unclefatfood',
    'cosmospeoplej',
    'kbtiest',
    'SetfireYC',
    'alisasa11111',
    'yuci7001',
    'chun.wang.987',
    'hanahomefood',
    'bigmimosa',
    'eggthings',
    'AnchormanRetina',
    'chuchushoeTW',
    'HuangDaChien',
    'cherng.y',
    '2uncle',
    'keven.yu.5',
    'chenchimai',
    'LuShiowYen',
    'twfreedomnews',
    'llchu',
    'skjawtime',
    'forpeople',
    'IsShow',
    'vivianhsu0319',
    'heyitskimberley',
    'JamHsiao',
    'KennyKhoo.QiuFengZe',
    '2203rchord420',
    'aaronyanmusic',
    'kuohsingchuntaiwan',
    'chuangchihyuan.com.tw',
    'judoywyang',
    'pojung0909',
    '100044303655589',
    'ili.cheng',
    'SMALLWINNI',
    'taitaifirsthome',
    'yanglynnwu',
    'CamerabayAbe',
    'cheapAOE',
]]

if __name__ == '__main__':
    print(set([x for x in page_list if page_list.count(x) > 1]))